### ISSUE TITLE
对于json-server的增改功能，home.js中wx.request()方法中data值应该是什么

### ISSUE THREAD

**Issue by BobMing** [ruanyf/wechat-miniprogram-demos#2]
比如按照原教程，db.json维持原样，仅有字符串数组"items": ["事项A", "事项B", "事项C"]，若想增加一个"事项D"，直接将其作为data的值POST请求给url:"http://localhost:3000/"，会报错400

SyntaxError: Unexpected token &#39;&quot;&#39;, &quot;&quot;D&quot;&quot; is not valid JSON<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError

即便对“事项D”先使用JSON.stringify()也是一样的结果。

**Comment by BobMing** [comment]
网上的教程都是以标准JSON对象数组为db.json的内容，POST的对象也是标准的JSON对象，我试了，自然是毫无问题。
但面对普通字符串数组时，这个data究竟应该怎么是个什么值呢？

**Comment by BobMing** [comment]
data: {"key": 3, "value":"事项D"}
报错500，TypeError: Cannot read properties of undefined (reading 'id')

data: {"id": 3, "value":"事项D"}
报201，但
```
"items": [
    "事项A",
    "事项B",
    "事项C",
    {
      "id": 3,
      "value": "事项D"
    }
  ]
```

**Comment by ruanyf** [comment]
操作数组的单个成员，需要有 id 属性。
https://www.npmjs.com/package/json-server#getting-started
